### ISSUE TITLE
Why is prev_samples = 2 * dequantized ?

### ISSUE THREAD

**Issue by qbx2** [deepsound-project/samplernn-pytorch#7]
https://github.com/deepsound-project/samplernn-pytorch/blob/master/model.py#L203

What is the purpose of multiplying by 2?

**Comment by koz4k** [comment]
It's so that dequantized samples are from the [-2, 2] interval. According to the autors, it's "a reasonable range to pass as inputs to the RNN". See the original implementation in Theano: https://github.com/soroushmehr/sampleRNN_ICLR2017/blob/master/models/two_tier/two_tier.py#L250

**Comment by qbx2** [comment]
Does it need to be multiplied by 2 even while reconstruction, then?

**Comment by koz4k** [comment]
Yes, it's so that the RNN learns better in the early stages of training. I'm not sure what's the reasoning behind this specifing value of the scaling factor, but I can say that the standard deviation of the sine wave on [-2, 2] interval is `sqrt(2) / 2 ~= 1.4`, so the std of the typical input should probably be somewhere between 0 and that value (we typically want the std of the input to be around 1).
